class RobotException(RuntimeError):

    ROBOT_EXIT_ON_FAILURE = True
